### ISSUE TITLE
Missing field for telemetry

### ISSUE THREAD

**Issue by Z3nk** [GPLNature/pubgapi#2]
Hi and thanks you for your API helper.

There is a field that needed to be add on telemetry :

**LogObjectInteraction**
 
Exemple of code :
` val pu = PubgClient()
        return pu.getTelemetry("https://telemetry-cdn.playbattlegrounds.com/bluehole-pubg/steam/2019/10/20/13/53/f52934db-f340-11e9-9357-0a586469f492-telemetry.json")`

Stacktrace : 

`java.lang.ClassNotFoundException: com.github.gplnature.pubgapi.model.telemetry.event.LogObjectInteraction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.gplnature.pubgapi.api.AbstractPubgClient.lambda$new$3(AbstractPubgClient.java:141)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
	at com.github.gplnature.pubgapi.util.RetrofitUtil.getResponse(RetrofitUtil.java:15)
	at com.github.gplnature.pubgapi.api.PubgClient.getTelemetry(PubgClient.java:101)`

Thanks

**Comment by GPLNature** [comment]
Sorry to see you too late.
We updated about this.
